[phases.setup]
nixPkgs = ["python3", "python3Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r backend/requirements.txt"]

[start]
cmd = "gunicorn backend.app:app --bind 0.0.0.0:$PORT"
